### ISSUE TITLE
autofill username field for a logged out user with 'username' data in cookie still set

### ISSUE THREAD

**Issue by RootCellar** [lavalo98/MockNetflixSiteCS372#11]

**Comment by lavalo98** [comment]
Maybe consider adding a remember username checkbox and people can opt into that functionality

**Comment by RootCellar** [comment]
I attempted this a few different ways, but couldn't get PUG to set the value of the textBox to the variable `username`.

**Comment by lavalo98** [comment]
Inside the parenthesis after the input put value=username

**Comment by RootCellar** [comment]
PUG has been edited and it seems to work since it no longer throws errors, but this isn't 100% testable until we have a working log-out button.

**Comment by RootCellar** [comment]
After log out functionality was added, this was shown to work!
