### ISSUE TITLE
limit movies watched per user to 3 per day

### ISSUE THREAD

**Issue by RootCellar** [lavalo98/MockNetflixSiteCS372#19]
the current count towards the limit is incremented as soon as the user starts watching the movie

**Comment by lavalo98** [comment]
This seems like a cookies thing to me, I think @RootCellar should take this one. We could always make it a database thing on the users profile but I'm not sure that that is the best way to go about it.

**Comment by RootCellar** [comment]
Implemented, seems to work, however it is slightly non user-friendly at the moment because it simply kicks the user back to `/home` with no explanation. Also, I don't currently know if it actually resets after the 24 hour mark or not.
